# Teacher-authored training sentences, English, second batch: terse and mobile styles, implied asks,
# long-winded business phrasing, and hard negatives that borrow request words. Same domains as
# en-train.py (legal, accounting, real estate, HR, e-commerce, freelance, product, travel, insurance, construction).
D = []
def g(act, action, *s): D.append((act, action, list(s)))

# ---- ASK in other registers ----
g('ASK','pay',
 "pls pay inv 4410 asap",
 "Hi, a gentle reminder that the invoice from August is still unpaid. Could you arrange the transfer?",
 "We haven't received the monthly fee yet, could you look into it and send it over?",
 "Would it be possible to settle the outstanding amount before the quarter closes?",
 "Can you chip in your share of the cabin, it's $240 each?",
 "Any news on the wire? Our accountant is closing the books tomorrow.",
 "I'd appreciate it if you could clear the remaining balance this week.",
 "Please process the refund to the original card, the customer has been waiting since the 2nd.",
 "The late fee will apply on Monday unless the payment reaches us.",
 "Could we get the advance transferred today so the crew can start?")
g('ASK','sign',
 "Sign here pls",
 "Whenever you get a moment, could you put your signature on the last page?",
 "The bank requires both of you to sign. Could you each sign the attached and send back?",
 "I've attached the waiver, please sign and return it before the trip.",
 "could you docusign the thing i sent? takes 1 min",
 "We're ready to close once the seller countersigns, can you nudge them?",
 "Please get the director to sign the resolution.",
 "Mind adding your signature to the delivery receipt?")
g('ASK','approve',
 "ok to proceed?",
 "Can I get your blessing on the revised timeline?",
 "Do I have your approval to book the venue?",
 "Please let me know if the attached terms are acceptable so I can issue the PO.",
 "I need you to greenlight the hire today or we lose the candidate.",
 "Would you be comfortable approving the change order?",
 "Is it alright with you if I send the draft to the client as is?",
 "We can't start until you approve the quote.")
g('ASK','confirm',
 "u still on for tues?",
 "Please confirm receipt.",
 "Can you reconfirm the flight times? The airline changed the schedule.",
 "Could you verify that the amount in the contract matches the quote?",
 "Just want to make sure you received the keys, can you confirm?",
 "Is this the final version? Please confirm before I print 500 copies.",
 "I'd like you to confirm in writing that the work is complete.",
 "Please check that your insurance certificate is still valid and let me know.",
 "Am I right that the deadline is the 15th? Please confirm.")
g('ASK','schedule',
 "free for 15 min later?",
 "Let's grab coffee next week, what day is good for you?",
 "Could you give me a few windows that work for a call with the architect?",
 "I'd like to set up an exit interview, when would suit you?",
 "Are you able to meet at the property on Wednesday at 3?",
 "Please send me your availability for the contract review.",
 "Shall we lock in the 9th for the launch?",
 "Can we push the deadline by a week? Let me know what works.",
 "Can you suggest a date for the final walkthrough?")
g('ASK','decide',
 "A or B?",
 "Which colourway do you prefer, the navy or the grey?",
 "We need you to choose the insurance tier before the window closes.",
 "Are you going to accept the offer or not? They need to know by noon.",
 "Do you want me to cancel the order or wait for the backorder?",
 "Which hotel should I book, the one by the station or the one by the beach?",
 "Please advise how you'd like to proceed with the claim.",
 "Tell me which date you'd like and I'll lock it in.")
g('ASK','review',
 "thoughts?",
 "Can someone take a look at this error? It started after the deploy.",
 "I'd be grateful if you could cast an eye over the lease before I sign.",
 "Please sanity check the pricing table.",
 "Could you give the logo concepts a once-over and tell me which ones to drop?",
 "Would you mind checking whether the numbers tie to the ledger?",
 "Please review and let me know if it's good to send.",
 "What do you think of the new landing page copy?",
 "Could you assess the damage photos and tell me if this is covered?")
g('ASK','join',
 "u coming thurs?",
 "We'd be delighted if you could join us for the grand opening, please let us know.",
 "Please confirm whether you'll attend the shareholders' meeting.",
 "Can you sit in on the interview with me tomorrow?",
 "Are you able to come to the site inspection?",
 "RSVP by the 12th, we need numbers for catering.",
 "Could you join the thread so we have everyone in one place?")
g('ASK','complete',
 "pls update the spreadsheet w/ the new numbers",
 "Could you tidy up the footnotes and resubmit the document?",
 "We need the risk assessment finished before the permit hearing.",
 "Can you build the staging environment this week?",
 "Please assemble the closing binder.",
 "Would you prepare a short summary of the claim for the adjuster?",
 "Can you redo the render with the lighter flooring?",
 "Fill in the missing fields in the application and resubmit.")
g('ASK','send',
 "need the pdf",
 "Send me the address pls",
 "Can you ping me the tracking number?",
 "Would you be able to share the audit report with the new partner?",
 "I don't have the lease anymore, could you resend it?",
 "Please provide proof of address and a recent utility bill.",
 "Could you drop the files into the shared drive?",
 "I need the architect's drawings to submit with the permit, can you pass them on?",
 "Please attach your CV and portfolio to your reply.",
 "Can you email me a copy of the policy document?")
g('ASK','reply',
 "Hello, any news?",
 "r u there?",
 "Is the apartment still available?",
 "Sorry to chase, but could you please let me know where this stands?",
 "I'm still waiting to hear back on the quote, can you update me?",
 "Does the offer still stand?",
 "Please advise on next steps.",
 "Can you tell me when the technician is coming?",
 "What happened with the claim? Nobody has called me back.",
 "How is the refund going? It's been three weeks.",
 "Have the keys been released yet?",
 "Did anything come back from the lab?",
 "When will the order ship? The tracking hasn't moved.",
 "Wondering if you had a chance to think about my offer.",
 "Can you clarify what you meant by the second paragraph?",
 "Do you know who approves exceptions to the policy?")

# ---- PROMISE in other registers ----
g('PROMISE','pay',
 "will pay friday",
 "I'm sending the money now, give it a day to land.",
 "We'll clear the balance on the 1st when the funds arrive.",
 "I'll get accounting to release the payment this week.")
g('PROMISE','sign',
 "Will sign and send back tonight.",
 "I'll have the director sign the resolution this afternoon.",
 "We'll get both signatures by Monday.")
g('PROMISE','approve',
 "I'll give you the green light this afternoon.",
 "Approving now.",
 "We'll sign off on the quote once the numbers are corrected.")
g('PROMISE','confirm',
 "I'll reconfirm the flight times and message you.",
 "Will check the amounts and confirm tomorrow.",
 "I'll make sure the keys were received and let you know.")
g('PROMISE','schedule',
 "I'll find a slot and send it over.",
 "Let me look at the calendar and propose a few times.",
 "We'll lock in the 9th and send the invite.",
 "I'll book the walkthrough for Wednesday.")
g('PROMISE','decide',
 "I'll choose the colourway by tomorrow noon.",
 "We'll come to a decision after the board meets.",
 "I'll tell you which date works once I check with my team.")
g('PROMISE','review',
 "will have a look tonight",
 "I'll sanity check the pricing table and let you know.",
 "We'll go through the documents and revert with questions.",
 "I'll take a quick look and ping you.")
g('PROMISE','join',
 "I'll join the call.",
 "We'll be there, see you at the opening.",
 "I'll sit in on the interview.",
 "I'll come to the inspection on Wednesday.")
g('PROMISE','complete',
 "will update the spreadsheet today",
 "I'll tidy up the footnotes and resubmit.",
 "We'll build the staging environment by Friday.",
 "I'll prepare the claim summary this afternoon.",
 "I'll get the risk assessment done before the hearing.")
g('PROMISE','send',
 "sending now",
 "Will send the tracking number once it's issued.",
 "I'll pass the drawings on to you today.",
 "We'll drop the files in the shared drive by end of day.",
 "I'll email you a copy of the policy shortly.",
 "I'll resend the lease tonight.")
g('PROMISE','reply',
 "will get back to u",
 "I'll let you know when the technician is scheduled.",
 "We'll come back with next steps on Monday.",
 "I'll chase the adjuster and update you.",
 "Give me a day and I'll clarify.",
 "I'll check with the landlord and tell you what he says.",
 "Our team will be in touch shortly.")

# ---- INFORM that borrows request or promise words ----
g('INFORM','none',
 "Please note the office will be closed on Friday.",
 "Please see the attached for details.",
 "Kindly be advised that rates have changed.",
 "We would appreciate your patience during the renovation.",
 "I need to be honest, the numbers look weak this quarter.",
 "I will be out of office until the 14th with limited access to email.",
 "He will review the contract next week, I believe.",
 "She said she'd send the keys but I haven't seen them.",
 "The plan is to sign the lease in March.",
 "You will receive a confirmation email shortly.",
 "Remember, the deadline for filing is April 15.",
 "I'd like to point out that the clause was in the first draft too.",
 "Sending good vibes your way.",
 "Please accept our sincere apologies for the inconvenience.",
 "I sent it yesterday.",
 "As promised last week, the documents were uploaded on Monday.",
 "The vendor will send the invoice directly to accounting.",
 "We pay all suppliers on the 25th of each month.",
 "Could be worth looking at the second option too, but it's your call.",
 "You may need to renew the permit next year.",
 "I tried calling you twice this morning.",
 "Let's hope the weather holds.",
 "We expect the shipment to arrive next Thursday.",
 "Please don't hesitate to reach out if you have any questions.",
 "Waiting for the flight now, boarding in twenty minutes.",
 "The report is due Friday and the review happens Monday.",
 "Whoever approved this invoice made a mistake.",
 "What a week it has been.",
 "The auditors want everything by month-end, as usual.",
 "No update yet, still waiting on the lab.")

# ---- ACK ----
g('ACK','none',
 "thanks!!",
 "Great, thank you for letting me know.",
 "Awesome, talk soon.",
 "Brilliant, that's exactly what I needed.",
 "Fair enough.",
 "Thanks for the heads-up.",
 "Looks good, thank you.",
 "Thank you so much for your help with this.",
 "Yes please, that would be great.",
 "Perfect, thanks!",
 "Cool, see you later.",
 "That's fine by me.",
 "Totally understand, no stress.",
 "Thanks, I owe you one.",
 "Many thanks and happy holidays!",
 "Pleasure doing business with you.",
 "Hi Sam, hope you had a lovely weekend.",
 "Hope the family is well.",
 "Thanks for your quick response.",
 "Thanks, noted.",
 "Appreciate you following up.",
 "Welcome aboard!",
 "Well done on closing the deal!",
 "Good luck with the interview!")

if __name__ == '__main__':
    import json, sys
    out = []
    for act, action, ss in D:
        for t in ss:
            out.append({'t': t, 'act': act, 'action': action, 'lang': 'en', 'src': 'teacher'})
    json.dump(out, sys.stdout, ensure_ascii=False, indent=0)
