# Teacher-authored training sentences (English). Written by hand (by the teacher model, Claude),
# NOT generated from the grammar in scripts/intent/generate.cjs, and NOT used for evaluation.
# Domains here: legal, accounting, real estate, HR/recruiting, e-commerce support, freelance/creative,
# product/engineering, travel, insurance, construction. The held-out eval file uses OTHER domains.
# Format: (act, action, [sentences])
D = []
def g(act, action, *s): D.append((act, action, list(s)))

# ---------------- ASK ----------------
g('ASK','pay',
 "Can you wire the retainer before we start on Monday?",
 "Still waiting on the second installment, any ETA on the transfer?",
 "Please settle invoice 2291 by the 30th.",
 "Would you be able to refund the duplicate charge this week?",
 "The balance of $3,450 is overdue, please remit today.",
 "hey did the payment go out yet? finance is asking me",
 "We need the deposit in our account to hold the date.",
 "Kindly arrange payment of the attached bill within 14 days.",
 "Could you send the reimbursement for the flights? It's been a month.",
 "Is it possible to pay the remainder in two parts by Friday?",
 "Don't forget the transfer for the venue, they close the booking tomorrow.",
 "The card on file was declined, can you update it or pay by bank transfer?")
g('ASK','sign',
 "Could you countersign the engagement letter and send it back?",
 "Please sign page 4 and initial the amendments.",
 "We need your signature on the lease before the keys can be released.",
 "can u sign the NDA tonight? the other side wants it first thing",
 "Would you mind e-signing the DocuSign I just sent?",
 "Your signature is still missing on the power of attorney.",
 "Please return the signed purchase agreement by noon tomorrow.",
 "Dad needs to sign the school form too, can you get him to?",
 "The notary will only see you if the affidavit is signed beforehand, so please sign it.",
 "Can you wet-sign the original and courier it to us?")
g('ASK','approve',
 "Can you approve the budget so procurement can place the order?",
 "Please sign off on the revised scope by end of day.",
 "Need your go-ahead on the attached design before we send it to print.",
 "Could you OK the expense report? It's been in your queue since Tuesday.",
 "Are you fine with the new clause 7? I need a yes or no.",
 "Waiting for your approval to release the build.",
 "Would you authorize the extra two days of work?",
 "Please confirm that I can go ahead with the vendor you shortlisted.",
 "Is the refund approved? The customer keeps writing in.",
 "Just need a thumbs up from you and we're good to launch.")
g('ASK','confirm',
 "Can you confirm the delivery address is still 14 Harbor Street?",
 "Please verify the spelling of your name for the certificate.",
 "Could you double-check the totals in column D?",
 "Just confirming you got my last email, can you reply with a quick yes?",
 "Can you confirm the attendee count by Thursday so the caterer can order?",
 "Please validate the IBAN, the bank rejected the last payment.",
 "Are the dates March 3-5 still right on your side?",
 "Do you confirm that the figures in the attached statement are correct?",
 "Let me know that the wire arrived, I want to close this out.",
 "Can you ack receipt of the contract so I can stop chasing?")
g('ASK','schedule',
 "Can we find 30 minutes this week to go through the redlines?",
 "When are you free for a quick call tomorrow?",
 "Could you propose two times that work for the walkthrough?",
 "Let's book the closing for the 18th, does 10am work for you?",
 "Please pick a slot for the interview from the link below.",
 "can we move our sync to thursday? i have a conflict",
 "Would next Tuesday afternoon suit you for the site visit?",
 "What does your calendar look like on the 12th? I want to set up the deposition.",
 "I'd like to reschedule the inspection, what dates can you offer?",
 "Are you around Friday morning for a ten minute catch-up?")
g('ASK','decide',
 "Which of the two quotes do you want to go with?",
 "Please decide between option A and option B by Wednesday.",
 "Do you want us to renew the policy or let it lapse?",
 "We need a decision on the logo before Friday, which direction?",
 "Tell me whether you'd rather take the buyout or stay on.",
 "Should we proceed with the inspection or walk away?",
 "Have you chosen a candidate yet? The other offers expire Monday.",
 "Pick one: monthly billing or annual with the discount.",
 "Let me know whether you are in or out for the Q4 campaign.",
 "Do you want the extended warranty? I need an answer to finalize the order.")
g('ASK','review',
 "Could you take a look at the draft and send me comments?",
 "Would you mind proofreading the cover letter before I submit it?",
 "Any feedback on the mockups? I'd like to iterate tonight.",
 "Please review clause 12, I think the indemnity is off.",
 "Can you check my math on the amortization table?",
 "I'd love your thoughts on the pitch before Thursday.",
 "Mind giving the PR a quick review? It's blocking the release.",
 "Please look over the contract and flag anything unusual.",
 "Could you read through the offer letter and tell me if anything looks wrong?",
 "Do you have notes on the proposal? I'm sending it out tomorrow.")
g('ASK','join',
 "Can you make it to the kickoff on Monday at 9?",
 "Please RSVP for the closing dinner by Friday.",
 "Will you be joining the board call? We need quorum.",
 "Are you coming to the open house on Saturday? Let me know headcount.",
 "Could you attend the mediation on the 22nd?",
 "Please register for the webinar using the link below.",
 "we'd love to have you at the offsite, can you confirm you're in?",
 "Can you dial in to the partner meeting at 4?",
 "Do come to the signing ceremony, but tell us if you can make it.")
g('ASK','complete',
 "Please fill out the onboarding form before your first day.",
 "Can you finish the slides for the investor update by Thursday?",
 "Could you prepare the disclosure schedule for the data room?",
 "We need the tax questionnaire completed and returned.",
 "Please fix the failing test on the checkout branch.",
 "Can you draft the press release so legal can review it tomorrow?",
 "Would you update the cap table with the new grants?",
 "Please complete the vendor registration, procurement can't pay you without it.",
 "Could you write up the incident summary for the insurer?",
 "Finish the punch list items before the final walkthrough, please.")
g('ASK','send',
 "Could you send me the signed copy when you get a chance?",
 "Please forward the receipt for the hotel.",
 "Can you share the Figma link with the new developer?",
 "I still need your passport scan for the visa application.",
 "Send over the last three payslips please.",
 "Do you have the floor plan PDF? Could you email it to me?",
 "can you attach the invoice to the thread, accounting can't find it",
 "Please upload the inspection report to the shared folder.",
 "Mind sending me the vendor's W-9?",
 "Would you resend the link? The old one expired.",
 "Please provide your bank details so we can process the payout.",
 "Could you get me the contact details for your accountant?")
g('ASK','reply',
 "Any update on the contract?",
 "Why hasn't the shipment arrived yet? It was due Monday.",
 "Did you get a chance to look at my proposal? Let me know either way.",
 "Please get back to me today, the client is waiting.",
 "Hello? Just checking whether you saw my last message.",
 "What's the status of the permit application?",
 "Could you let me know if the apartment is still available?",
 "Any luck with the landlord?",
 "Please respond by Friday so I can close the file.",
 "I haven't heard back about the refund. Can you tell me where it stands?",
 "Where are we on the audit? I need something to tell the board.",
 "Quick question: does the warranty cover water damage?",
 "How long will the repair take? I need to plan around it.",
 "Following up on my email from last week, thoughts?",
 "Can you tell me which warehouse the order shipped from?",
 "Did the buyer ever reply about the counteroffer?")

# ---------------- PROMISE ----------------
g('PROMISE','pay',
 "I'll wire the deposit tomorrow morning.",
 "We will settle the invoice by the end of the week.",
 "Payment is going out today, you'll have it by Thursday.",
 "I'll refund the duplicate charge as soon as I'm back at my desk.",
 "Consider the balance paid, I'm transferring it this afternoon.",
 "We'll cover the flights and reimburse you with the next payroll.")
g('PROMISE','sign',
 "I'll sign the lease tonight and scan it over.",
 "We will countersign and return the agreement by Friday.",
 "I can get the NDA signed this afternoon.",
 "I'll drop by the notary tomorrow and send you the stamped copy.",
 "Will sign it first thing in the morning, promise.")
g('PROMISE','approve',
 "I'll approve the budget as soon as finance signs off.",
 "We'll give you the go-ahead by Wednesday.",
 "I'll OK the expense report this afternoon.",
 "I will authorize the extra hours once I see the revised estimate.")
g('PROMISE','confirm',
 "I'll confirm the delivery window with the carrier and let you know.",
 "We'll verify the figures tonight and come back to you.",
 "I will double-check the address with the customer tomorrow.",
 "Let me confirm with legal and get back to you in an hour.")
g('PROMISE','schedule',
 "I'll book the site visit for next week and send an invite.",
 "We'll find a time on Thursday and message you the options.",
 "Let me set up the call with both lawyers.",
 "I will reschedule the inspection and confirm the new date today.")
g('PROMISE','decide',
 "I'll decide on the vendor by Friday.",
 "We'll let you know our decision before the offer expires.",
 "I'll make up my mind this weekend and tell you Monday.")
g('PROMISE','review',
 "I'll read through the draft tonight and send comments.",
 "We will review the contract on our side and revert by Tuesday.",
 "I'll take a look at the mockups first thing tomorrow.",
 "Let me look over the clause and get back to you.",
 "I will proofread it this evening.")
g('PROMISE','join',
 "I'll be at the kickoff on Monday.",
 "We will attend the mediation on the 22nd.",
 "I'll dial in to the board call at 4.",
 "Count me in for the offsite, I'll register today.")
g('PROMISE','complete',
 "I'll finish the slides by Thursday.",
 "We will have the disclosure schedule ready for the data room tomorrow.",
 "I'll fix the failing test today.",
 "I'll write up the incident summary and share it before noon.",
 "I'm on it, the punch list will be done before the walkthrough.",
 "I will complete the form tonight.")
g('PROMISE','send',
 "I'll send the signed copy over this afternoon.",
 "I will forward the receipt in a few minutes.",
 "We'll share the Figma link once the file is cleaned up.",
 "Will email you the floor plan shortly.",
 "I'll upload the inspection report to the folder tomorrow.",
 "I can get you the contact details for our accountant by tonight.",
 "Expect the W-9 in your inbox before lunch.",
 "I'll resend the link right now.")
g('PROMISE','reply',
 "I'll get back to you tomorrow with an answer.",
 "We will update you as soon as we hear from the landlord.",
 "Let me check and revert by end of day.",
 "I'll let you know once the permit comes through.",
 "Will reply properly after the weekend.",
 "I'll keep you posted on the audit.",
 "You'll hear from us by Friday.",
 "Our recruiter will contact you within two business days.",
 "I'll follow up with the buyer and report back.")

# ---------------- INFORM ----------------
g('INFORM','none',
 "The refund was issued on Tuesday and should show up within a week.",
 "The landlord said the deposit will be returned within thirty days of move-out.",
 "I have been working with the contractor on the plan since January.",
 "Our offices are closed on the 25th and 26th.",
 "The inspection found minor damp in the basement.",
 "Invoice 2291 was sent on the 3rd.",
 "Payment terms in the contract are net 30.",
 "The new policy takes effect on January 1.",
 "Your order shipped this morning via DHL, tracking number below.",
 "Revenue grew 12% quarter over quarter.",
 "The buyer's lawyer is based in Rotterdam.",
 "I was out sick on Monday and Tuesday.",
 "The meeting ran long, we covered the budget and the hiring plan.",
 "Version 2.3 fixes the login bug but not the export issue.",
 "I think the estimate is a bit optimistic.",
 "The venue holds around 120 people.",
 "We received your application on March 3.",
 "Her flight lands at 6:40 and the hotel is ten minutes away.",
 "Our records show the account was closed in 2021.",
 "That clause was added after the second round of negotiations.",
 "The candidate has five years of experience in logistics.",
 "It rained all week so the roof work is delayed.",
 "Dana signed the lease last Friday.",
 "We already paid the invoice on the 14th.",
 "The offer letter is dated March 3 and valid for one week.",
 "The warranty covers manufacturing defects for two years.",
 "Parking is free after 6 pm.",
 "Interest rates are expected to hold steady this quarter.",
 "As discussed, the deposit is non-refundable.",
 "The contractor mentioned the permit might take six weeks.",
 "Attached you'll find the statement for September.",
 "Please find the minutes of last week's meeting below.",
 "FYI the shipment cleared customs this morning.",
 "Heads up, the portal will be down on Sunday night.",
 "Nothing needed from you on this one, just keeping you in the loop.",
 "My assistant has your file and is processing it.",
 "He promised to send the report last month but never did.",
 "If the deal falls through we will lose the deposit.",
 "The review is scheduled for the 9th, in room 4.",
 "Your account balance is $1,204.50.")

# ---------------- ACK ----------------
g('ACK','none',
 "Thanks, that's really helpful.",
 "Got it, thank you!",
 "Perfect, see you then.",
 "Sounds good to me.",
 "Great news, congratulations!",
 "Appreciate the quick turnaround.",
 "No worries at all, take your time.",
 "Thanks for sending this over.",
 "All the best with the move!",
 "Happy new year to you and the family.",
 "Hope you have a restful weekend.",
 "Noted, thanks for flagging.",
 "Will you be at the conference this year? Would be great to catch up.",
 "How was the trip?",
 "Looking forward to it!",
 "Thank you for your patience.",
 "Wonderful, that works.",
 "Cheers!",
 "ok thx",
 "Understood.",
 "Lovely to meet you yesterday.",
 "Thanks again for lunch, it was great.",
 "Have a good one!",
 "Sorry for the late reply.",
 "That makes sense, thanks for explaining.",
 "Congrats on the new role!",
 "Best regards, Alex",
 "Thank you, much appreciated.",
 "Please give my regards to the team.",
 "Safe travels!",
 "Great seeing everyone at the party.",
 "Good morning!",
 "Can you believe how fast this year went?",
 "Enjoy the holiday!")

if __name__ == '__main__':
    import json, sys
    out = []
    for act, action, ss in D:
        for t in ss:
            out.append({'t': t, 'act': act, 'action': action, 'lang': 'en', 'src': 'teacher'})
    json.dump(out, sys.stdout, ensure_ascii=False, indent=0)
