#!/usr/bin/env node
// Generates the signing key pair for community deltas (ECDSA P-256). The PUBLIC key is written into
// flow-trial-extension/core/community-key.js (commit it: the extension uses it to verify). The PRIVATE key is
// printed ONCE; put it in your secret store as COMMUNITY_PRIVATE_KEY_PEM and never commit it.
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { publicKey, privateKey } = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' });
const jwk = publicKey.export({ format: 'jwk' });
const out = '// GENERATED by scripts/community/generate-keys.cjs. The PUBLIC verification key for signed community deltas.\n// null = community learning has no key yet, so no delta can ever be applied (the safe default).\nconst FlowCommunityKey = ' + JSON.stringify({ kty: jwk.kty, crv: jwk.crv, x: jwk.x, y: jwk.y }) + ';\nif (typeof module !== \'undefined\') module.exports = { FlowCommunityKey };\n';
fs.writeFileSync(path.join(__dirname, '..', '..', 'flow-trial-extension', 'core', 'community-key.js'), out);
console.log('Public key written to flow-trial-extension/core/community-key.js. Commit it.\n');
console.log('PRIVATE KEY (store as COMMUNITY_PRIVATE_KEY_PEM, shown once, never commit):\n');
console.log(privateKey.export({ type: 'pkcs8', format: 'pem' }));
