#!/usr/bin/env node
// Vendors the two files the on-device model needs into flow-trial-extension/vendor/, reproducibly and with every input verified:
//   vendor/web-llm.js                              @mlc-ai/web-llm 0.2.85 (Apache-2.0), tree-shaken to CreateMLCEngine and minified with a pinned esbuild
//   vendor/Phi-3-mini-4k-instruct-q4f16_1-MLC-webgpu.wasm   the model library (CODE: it must be a file of the package, never fetched at run time)
// docs/hybrid-execution-architecture.md. Run from the repo root on a machine with npm and network access:  node scripts/hybrid/vendor-runtime.cjs
// Budget: the owner accepted at most +12 MB for the runtime and the WASM (2026-10-04). The script fails if the two files together exceed it.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const WEBLLM = { name: '@mlc-ai/web-llm', version: '0.2.85', integrity: 'sha512-CwUiSAvDCYnmAZlpPMkurPHDfBLq6fvdRB3vRgoA894hRG/V/BSeY9bmMm6iIIU5VpjJxfb/dLPpJX2at0L9rw==' };
const ESBUILD_VERSION = '0.28.2';
const BUDGET_BYTES = 12 * 1000 * 1000;
const ROOT = path.join(__dirname, '..', '..');
const OUT = path.join(ROOT, 'flow-trial-extension', 'vendor');
const MANIFEST = JSON.parse(fs.readFileSync(path.join(ROOT, 'flow-trial-extension', 'core', 'model-manifests', 'Phi-3-mini-4k-instruct-q4f16_1-MLC.json'), 'utf8'));
const tmp = fs.mkdtempSync(path.join(require('os').tmpdir(), 'glance-vendor-'));
const sh = (cmd, args, cwd) => execFileSync(cmd, args, { cwd: cwd || tmp, stdio: ['ignore', 'pipe', 'inherit'] }).toString();
const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');
fs.mkdirSync(OUT, { recursive: true });

// 1. the npm tarball, verified against the integrity hash pinned above (the registry's own answer is not trusted)
const tgz = sh('npm', ['pack', WEBLLM.name + '@' + WEBLLM.version, '--silent']).trim().split('\n').pop();
const sri = 'sha512-' + crypto.createHash('sha512').update(fs.readFileSync(path.join(tmp, tgz))).digest('base64');
if (sri !== WEBLLM.integrity) { console.error('web-llm tarball integrity mismatch:', sri); process.exit(1); }
sh('tar', ['xzf', tgz]);
fs.copyFileSync(path.join(tmp, 'package', 'LICENSE'), path.join(OUT, 'web-llm.LICENSE'));

// 2. a pinned esbuild, tree-shaken to the one export the offscreen page uses
sh('npm', ['install', '--silent', '--no-audit', '--no-fund', 'esbuild@' + ESBUILD_VERSION]);
fs.writeFileSync(path.join(tmp, 'entry.js'), "export { CreateMLCEngine } from './package/lib/index.js';\n");
sh(path.join(tmp, 'node_modules', '.bin', 'esbuild'), ['entry.js', '--bundle', '--minify', '--format=esm', '--target=chrome120', '--legal-comments=none', '--outfile=' + path.join(OUT, 'web-llm.js')]);

// 3. the model library, from the pinned commit, checked against the hash in the pinned manifest
const libName = 'Phi-3-mini-4k-instruct-q4f16_1-MLC-webgpu.wasm';
(async () => {
  const res = await fetch(MANIFEST.modelLib.url);
  if (!res.ok) { console.error('wasm download failed', res.status); process.exit(1); }
  const wasm = Buffer.from(await res.arrayBuffer());
  if (sha256(wasm) !== MANIFEST.modelLib.sha256) { console.error('wasm hash does not match the pinned manifest:', sha256(wasm)); process.exit(1); }
  fs.writeFileSync(path.join(OUT, libName), wasm);
  const js = fs.readFileSync(path.join(OUT, 'web-llm.js'));
  const total = js.length + wasm.length;
  fs.writeFileSync(path.join(OUT, 'VENDOR.json'), JSON.stringify({
    note: 'Generated by scripts/hybrid/vendor-runtime.cjs. Do not edit by hand.',
    webLlm: { package: WEBLLM.name, version: WEBLLM.version, tarballIntegrity: WEBLLM.integrity, esbuild: ESBUILD_VERSION, file: 'web-llm.js', bytes: js.length, sha256: sha256(js), license: 'Apache-2.0 (web-llm.LICENSE)' },
    modelLibrary: { file: libName, bytes: wasm.length, sha256: sha256(wasm), source: MANIFEST.modelLib.url, libRevision: MANIFEST.modelLib.libRevision },
    totalBytes: total, budgetBytes: BUDGET_BYTES
  }, null, 1) + '\n');
  console.log('vendored', { webLlmBytes: js.length, wasmBytes: wasm.length, totalMB: Math.round(total / 1e5) / 10, budgetMB: BUDGET_BYTES / 1e6 });
  if (total > BUDGET_BYTES) { console.error('OVER THE +12 MB BUDGET'); process.exit(2); }
})();
