#!/usr/bin/env python3
"""Builds flow-trial-extension/core/dense-prior-data.js: a small pretrained English word-vector table for the intent model.

  python3 scripts/intent/nn/build-dense-prior.py <glove-wiki-gigaword-100.txt.gz> [--vocab 20000] [--dim 32]

Source: GloVe 6B (Wikipedia 2014 + Gigaword 5), 100-d, Pennington, Socher, Manning 2014, released under the Public Domain
Dedication and License (PDDL 1.0). The top-N most frequent words are kept, each vector is unit-normalised, projected onto its
first --dim principal components (PCA), re-normalised and quantised to int8. English only: there is no equivalent Hebrew table.
"""
import gzip, sys, json, base64, argparse, os
import numpy as np
ap = argparse.ArgumentParser(); ap.add_argument('glove'); ap.add_argument('--vocab', type=int, default=20000); ap.add_argument('--dim', type=int, default=32)
a = ap.parse_args()
words = []; vecs = []
with gzip.open(a.glove, 'rt', encoding='utf8') as f:
    for line in f:
        p = line.rstrip().split(' ')
        if len(p) < 50: continue
        w = p[0]
        if not w.isalpha() or not w.isascii() or len(w) > 20: continue   # the model only sees [a-z]+ tokens
        words.append(w); vecs.append(np.asarray(p[1:], dtype=np.float32))
        if len(words) >= a.vocab: break
V = np.stack(vecs); V /= (np.linalg.norm(V, axis=1, keepdims=True) + 1e-6)
mu = V.mean(0); U, S, Vt = np.linalg.svd(V - mu, full_matrices=False)
P = (V - mu) @ Vt[:a.dim].T
P /= (np.linalg.norm(P, axis=1, keepdims=True) + 1e-6)
q = np.clip(np.round(P * 127), -127, 127).astype(np.int8)
out = {'dim': a.dim, 'scale': 127, 'n': len(words), 'words': ' '.join(words), 'b64': base64.b64encode(q.tobytes()).decode('ascii'),
       'source': 'GloVe 6B wiki-gigaword 100d (PDDL 1.0), top %d alphabetic words, PCA %d, int8' % (len(words), a.dim)}
dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..', 'flow-trial-extension', 'core', 'dense-prior-data.js')
js = '// GENERATED by scripts/intent/nn/build-dense-prior.py. Do not edit by hand.\n// ' + out['source'] + '\nconst FlowDensePriorData = ' + json.dumps(out) + ';\nif (typeof module !== \'undefined\') module.exports = { FlowDensePriorData };\n'
open(dst, 'w').write(js)
print('wrote', os.path.normpath(dst), round(len(js) / 1024), 'KB,', len(words), 'words')
