// GENERATED by scripts/community/generate-keys.cjs. The PUBLIC verification key for signed community deltas.
// null = community learning has no key yet, so no delta can ever be applied (the safe default).
const FlowCommunityKey = null;
if (typeof module !== 'undefined') module.exports = { FlowCommunityKey };
